// SPEC-71 — Financial Literacy App Guide redo. Pure data module holding the
// single expanded WiseWallet App Guide body. No React Native imports so the
// §1.10 jest guard can run under the `roots: utils` setup.

export const APP_GUIDE_CONTENT = `Getting Started:
Welcome to WiseWallet, your personal finance tracker. This guide walks you through every screen in the app.
1. Complete onboarding to set up your profile and opening balance.
2. During registration choose Online or Local account mode. Local accounts keep all data on this device.
3. Cash is your first payment method; add more payment methods and categories in Settings.
4. Set a 4-digit passcode when prompted to protect the app on open.

Using the Dashboard:
The Dashboard is your home screen with the health of your money at a glance.
1. The top card shows your Available to Spend balance.
2. Highlights summarize balances, upcoming dues, and savings progress.
3. Recent Activity lists the latest five transactions for quick review.
4. Use the circle + button beside the tab bar to add a transaction instantly.

Adding and Editing Transactions:
Transactions are the heart of WiseWallet, so their fields are worth knowing.
1. Choose income or expense, then enter the amount (up to the PHP 10,000,000 cap).
2. Select a category, payment method, and date; add an establishment and note for context.
3. Attach a receipt photo if you want a visual record of the purchase.
4. Edit or delete from the transaction details screen. Transactions generated by a scheduled due are locked on purpose.

Managing Categories and Payment Methods:
Customization keeps your tracking accurate.
1. Open Manage Categories to add, rename, or sort categories. Sort by Name, Type, or Recent.
2. Payment Methods stores the ways you pay, such as cash, cards, and e-wallets.
3. Every transaction requires a category and a payment method, so keep both up to date.

Tracking Scheduled Dues:
Never miss a bill with recurring and one-time schedules.
1. Add a due with a title, amount, category, payment method, and start date from the calendar picker.
2. Choose one-time or recurring. Auto-renew creates the next occurrence when the current one is paid.
3. Pay a due to record its transaction; you will be asked to confirm the payment method.
4. Completed dues move to the Completed Dues screen with This Week, This Month, and All filters.

Building Allocations:
Allocations turn savings goals into visible progress.
1. Create an allocation with a target amount and watch the progress bar fill as you transfer money in.
2. Finished allocations can be archived to keep your active list clean.
3. The Archived Allocations screen lets you restore a goal or delete it permanently.

Reading Reports and Exporting:
Reports help you understand where your money goes.
1. The income-vs-expense donut and monthly trend chart show your cash flow pattern.
2. Category breakdowns reveal which categories cost the most.
3. A caption always shows the exact period selected.
4. Export CSV or PDF from the Reports screen: mobile saves the file and offers Share, web uses the browser download or print flow.

Using the Calendar and Notifications:
Stay on top of dates and alerts.
1. The Calendar screen shows dues and transactions organized by day.
2. Local reminders can nudge you before a due date when available in your environment.
3. The Notifications screen lists system alerts such as an ended session or a negative balance.

Protecting Your Account:
Your data deserves a lock.
1. Set and change your 4-digit passcode from Settings; the app asks for it to open.
2. If your session is ended remotely, the app signs you out and shows a session-ended alert.
3. Local accounts can upgrade to Online with Make Online; there is no downgrade back to Local.
4. Never share your passcode or login email with anyone.

Managing Settings and Data:
Put the app to work the way you like.
1. Toggle dark mode and keep the Philippine Peso as your currency.
2. Export your data as a JSON backup and import it again on another device.
3. Clear Data wipes everything after passcode confirmation, so back up before clearing.
4. Online accounts can toggle Auto-Backup for automatic cloud copies.

Pro Tips:
Small habits make the biggest difference.
1. Record transactions promptly so your balance and reports stay accurate.
2. Check Reports weekly to spot spending leaks early.
3. Pay dues on time or reschedule them so they never surprise you.
4. Keep your passcode private and export a backup when you change devices.`;