name: CI

on:
  push:
    branches: [main, upgrade-expo, develop]
  pull_request:
    branches: [main]

jobs:
  lint-typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - run: npx eslint . --ext .ts,.tsx --max-warnings 999
        name: Lint

      - run: npx tsc --noEmit
        name: TypeScript check
